name: grandmas-cookbook


networks:

  cookbook-network:
    name: cookbook-network
    driver: bridge


volumes:

  mongodb-data:
    name: mongodb-data


services:

  recipes-api:
    restart: unless-stopped
    container_name: recipes-api
    image: recipes-api:0.1
    build:
      context: ./recipes-api
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
    environment:
      - RECIPES_PORT=50000
    networks:
      - cookbook-network
  
  database-api:
    restart: unless-stopped
    container_name: database-api
    image: database-api:0.1
    build:
      context: ./database-api
      dockerfile: Dockerfile
    ports:
      - "50001:50001"
    environment:
      - DATABASE_PORT=50001
    networks:
      - cookbook-network
    depends_on:
      - mongodb
  
  mongodb:
    restart: unless-stopped
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - cookbook-network
  
  cookbook-gateway:
    restart: unless-stopped
    container_name: cookbook-gateway
    image: cookbook-gateway:0.1
    build:
      context: ./cookbook-gateway
      dockerfile: Dockerfile
    ports:
      - "50002:50002"
    environment:
      - GATEWAY_PORT=50002
      - RECIPE_API_IP=load-balancer-recipes
      - RECIPE_API_PORT=50003
      - DATABASE_API_IP=database-api
      - DATABASE_API_PORT=50001
    networks:
      - cookbook-network
    depends_on:
      - recipes-api
      - database-api
  
  cookbook-web:
    restart: unless-stopped
    container_name: cookbook-web
    image: cookbook-web:0.1
    build:
      context: ./cookbook-web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - WEB_PORT=4200
      - GATEWAY_IP=cookbook-gateway
      - GATEWAY_PORT=50002
    networks:
      - cookbook-network
    depends_on:
      - cookbook-gateway
  
  load-balancer-recipes:
    restart: unless-stopped
    container_name: load-balancer-recipes
    image: load-balancer-recipes:0.1
    build:
      context: ./load-balancer-recipes
      dockerfile: Dockerfile
    ports:
      - "50003:50003"
    networks:
      - cookbook-network
    depends_on:
      - recipes-api